name: docker deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: replace localhost url
      run: sed 's@localhost@backend-alb-1352487503.us-west-2.elb.amazonaws.com' src/app/app.config.ts
        
    - name: build, tag, push
      run: docker build -t theneverendingstory/frontend . && docker tag theneverendingstory/frontend:latest 837720593432.dkr.ecr.us-west-2.amazonaws.com/theneverendingstory/frontend:latest && docker push 837720593432.dkr.ecr.us-west-2.amazonaws.com/theneverendingstory/frontend:latest
      
    - name: download task definition
      run: |
        aws ecs describe-task-definition --task-definition frontend --query taskDefinition > task-definition.json
        
    - name: fill in task definition
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1.6.2
      with:
        task-definition: task-definition.json
        container-name: frontend
        image: 837720593432.dkr.ecr.us-west-2.amazonaws.com/theneverendingstory/frontend

    - name: deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: frontend
        cluster: the-neverending-story-cluster
        wait-for-service-stability: true
