name: Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: lint
      run: npm ci && npm install -g @angular/cli && ng lint
